inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'test/**/*'
    - 'vendor/**/*'

Metrics:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/Lambda:
  Enabled: false

# enable both hash-rocket and ruby19 hashmap syntax
Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
